### ISSUE TITLE
Shadowgrounds: crashes at start using the GOG version

### ISSUE THREAD

**Issue by neuromancer** [vayerx/shadowgrounds#25]
Hi,

I compiled Shadowgrounds in ArchLinux. I have the [GOG version of the game](https://www.gog.com/game/shadowgrounds) (Windows only) and using innoextract got the data*.fbz files. Then I used the fix-files.sh:

```Archive:  /tmp/data1.fbz
  inflating: flamethrower_part1.txt  
  inflating: flamethrower_part2.txt  
  inflating: flamethrower_part3.txt  
  inflating: scavenger_gore.txt      
  inflating: splash.tga              
  adding: data/ (stored 0%)
  adding: data/models/ (stored 0%)
  adding: data/models/particles/ (stored 0%)
  adding: data/models/particles/emitter_shapes/ (stored 0%)
  adding: data/models/particles/emitter_shapes/soapy.tga (deflated 98%)
  adding: data/textures/ (stored 0%)
  adding: data/textures/particles/ (stored 0%)
  adding: data/textures/particles/fluids/ (stored 0%)
  adding: data/textures/particles/fluids/awter_splash.tga (deflated 76%)
  adding: data/effects/ (stored 0%)
  adding: data/effects/particles/ (stored 0%)
  adding: data/effects/particles/scavenger_gore_partial.txt (deflated 83%)
  adding: data/effects/particles/flamethrower_part3_low.txt (deflated 86%)
  adding: data/effects/particles/flamethrower_part2_low.txt (deflated 86%)
  adding: data/effects/particles/flamethrower_part1_low.txt (deflated 73%)
'data4.fbz' -> '/tmp/data4.fbz' 
```

But then, the game crashes at the start:

```Thread 1 "shadowgrounds" received signal SIGSEGV, Segmentation fault.
0x00007ffff0737414 in __memmove_sse2_unaligned_erms () from /usr/lib/libc.so.6
#0  0x00007ffff0737414 in __memmove_sse2_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007ffff4ec232c in  () at /usr/lib/libSDL-1.2.so.0
#2  0x00007ffff4a6cd1e in get_fileinfo (fr=0x555559c73020) at readers.c:378
#3  0x00007ffff4a6cd1e in default_init (fr=0x555559c73020) at readers.c:840
#4  0x00007ffff4a6d649 in open_stream (fr=fr@entry=0x555559c73020, bs_filenam=bs_filenam@entry=0x0, fd=fd@entry=0) at readers.c:935
#5  0x00007ffff4a6fd29 in mpg123_open_fd (mh=mh@entry=0x555559c73020, fd=fd@entry=0) at libmpg123.c:465
#6  0x00007ffff4a4fc51 in MPG123_open (sample=0x55555979a700, ext=<optimized out>) at mpg123.c:237
#7  0x00007ffff4a4c797 in init_sample (funcs=funcs@entry=0x7ffff4c808a0 <__Sound_DecoderFunctions_MPG123>, sample=sample@entry=0x55555979a700, ext=ext@entry=0x0, _desired=_desired@entry=0x0) at SDL_sound.c:492
#8  0x00007ffff4a4cdf1 in Sound_NewSample (rw=0x555559ca0960, ext=0x0, desired=0x0, bSize=<optimized out>) at SDL_sound.c:628
#9  0x00005555558cd8c7 in sfx::WaveReader::WaveReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x00005555558d02f8 in sfx::Sound::Data::Data(char const*, int) ()
#11 0x00005555558d3136 in sfx::SoundLib::loadSample(char const*) ()
#12 0x00005555558c8bd6 in sfx::SoundMixer::loadSample(char const*, bool) ()
#13 0x00005555555e4907 in game::GameUI::playSoundEffect(char const*, float, float, float, boxol, int, float, int, bool) ()
#14 0x00005555556bd7d8 in ui::MenuBaseImpl::CursorEvent(OguiButtonEvent*) ()
#15 0x000055555576f2d5 in ui::MainMenu::CursorEvent(OguiButtonEvent*) ()
#16 0x00005555557ade12 in ogui_button_event_handler(OguiButtonEvent::EVENT_TYPE) ()
#17 0x00005555557b15e2 in og_run_gui() ()
#18 0x0000555555796ae7 in Ogui::Run(int) ()
#19 0x00005555555a6d39 in main ()
```

Regards,
Gustavo

**Comment by vayerx** [comment]
Hello,
Thanks four your bug-report. Unfortunately, I couldn't reproduce it on my local machine.
Could you please build Shadowgrounds in debug mode and provide extended backtrace:

    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug ../
    make
    gdb ./shadowgrounds

and make full backtrace when the game crashes:

    (gdb) backtrace full

What compiler are you using? Which versions of SDL and mpg123 do you have? Are you building the latest commit (acb80fe) in linux branch?

**Comment by neuromancer** [comment]
I'm using the last commit of the linux branch:

```
$ cmake -DCMAKE_BUILD_TYPE=Debug ../
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:23 (FIND_PACKAGE)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:23 (FIND_PACKAGE)


CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:23 (FIND_PACKAGE)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   thread
--   system
-- Found SDL: /usr/lib/libSDLmain.a;/usr/lib/libSDL.so;-lpthread (found version "1.2.15") 
-- Found SDL_sound: /usr/lib/libSDL_sound.so (found version "1.0.1") 
-- Found VORBIS: /usr/include  
-- Found SDL_image: /usr/lib/libSDL_image.so (found version "1.2.12") 
-- Found SDL_ttf: /usr/lib/libSDL_ttf.so (found version "2.0.11") 
-- Found OpenGL: /usr/lib/libGL.so  
-- Found GTK2_GTK: /usr/lib/libgtk-x11-2.0.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found OpenAL: /usr/lib/libopenal.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.89.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.71.100
-- Checking for module 'libavdevice'
--   Found libavdevice, version 57.6.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.58.100
-- Checking for module 'libswscale'
--   Found libswscale, version 4.6.100
-- Checking for module 'libpostproc'
--   Found libpostproc, version 54.5.100
-- Found FFmpeg: /usr/lib/libavcodec.so;/usr/lib/libavformat.so;/usr/lib/libavutil.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/g/Games/shadowgrounds/build
```

and debug backtrace is here:

```
#0  0x00007ffff0737414 in __memmove_sse2_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007ffff4ec232c in  () at /usr/lib/libSDL-1.2.so.0
#2  0x00007ffff4a6cd1e in get_fileinfo (fr=0x555559fa4110) at readers.c:378
        len = <optimized out>
#3  0x00007ffff4a6cd1e in default_init (fr=0x555559fa4110) at readers.c:840
#4  0x00007ffff4a6d649 in open_stream (fr=fr@entry=0x555559fa4110, bs_filenam=bs_filenam@entry=0x0, fd=fd@entry=0) at readers.c:935
        filept_opened = <optimized out>
        filept = <optimized out>
#5  0x00007ffff4a6fd29 in mpg123_open_fd (mh=mh@entry=0x555559fa4110, fd=fd@entry=0) at libmpg123.c:465
#6  0x00007ffff4a4fc51 in MPG123_open (sample=0x555559ed1b60, ext=<optimized out>) at mpg123.c:237
        internal = 0x555559ed8c90
        mp = 0x555559fa4110
        rate = 0
        channels = 0
        fmt = 0
        rc = 0
        len = 0
        seekable = 0
        ptr = <optimized out>
        rwops = <optimized out>
#7  0x00007ffff4a4c797 in init_sample (funcs=funcs@entry=0x7ffff4c808a0 <__Sound_DecoderFunctions_MPG123>, sample=sample@entry=0x555559ed1b60, ext=ext@entry=0x0, _desired=_desired@entry=0x0) at SDL_sound.c:492
        internal = 0x555559ed8c90
        desired = <optimized out>
        pos = 0
#8  0x00007ffff4a4cdf1 in Sound_NewSample (rw=0x555559e6ef20, ext=0x0, desired=0x0, bSize=<optimized out>) at SDL_sound.c:628
        should_try = 1
        decoderExt = 0x7ffff4c81558 <extensions_mpg123+8>
        decoder = 0x7ffff4c813a0 <decoders>
#9  0x00005555559f95c1 in sfx::WaveReader::Data::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x5555573a8610, file="data/sounds/defaultfx/gui_menu_sound_mouseover.wav")
    at /home/g/Games/shadowgrounds/sound/WaveReader.cpp:65
---Type <return> to continue, or q <return> to quit---
        rw = 0x555559e6ef20
        size = 7890
        fileCont = 0x555559eed260
#10 0x00005555559f8f90 in sfx::WaveReader::WaveReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffffda10, file="data/sounds/defaultfx/gui_menu_sound_mouseover.wav")
    at /home/g/Games/shadowgrounds/sound/WaveReader.cpp:222
        newData = {px = 0x0}
#11 0x00005555559fac97 in sfx::Sound::Data::Data(char const*, int) (this=0x555559eed540, file=0x555559c83770 "data/sounds/defaultfx/gui_menu_sound_mouseover.wav", flags=0) at /home/g/Games/shadowgrounds/sound/openal/SoundLib.cpp:497
        reader = {data = {px = 0x5555573a8610}}
        isOgg = false
        buffer = std::vector of length 0, capacity 0
        format = 4355
#12 0x00005555559fe275 in sfx::SoundLib::loadSample(char const*) (this=0x555556e50840, file=0x555559c83770 "data/sounds/defaultfx/gui_menu_sound_mouseover.wav") at /home/g/Games/shadowgrounds/sound/openal/SoundLib.cpp:1757
        __PRETTY_FUNCTION__ = "sfx::Sound* sfx::SoundLib::loadSample(const char*)"
        locked = {m = 0x555556baaaa0, is_locked = true}
        newSound = 0x7b6f000ca82c3300
#13 0x00005555559ef54b in sfx::SoundMixer::Data::loadSample(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (this=0x5555564d76f0, filename="data/sounds/defaultfx/gui_menu_sound_mouseover.wav", temporaryCache=false)
    at /home/g/Games/shadowgrounds/sound/SoundMixer.cpp:352
        __PRETTY_FUNCTION__ = "sfx::SoundSample* sfx::SoundMixer::Data::loadSample(std::__cxx11::string, bool)"
        it = 
  {first = <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, second = 0x5555564d7758}
        sound = 0x32
        sample = 0x7b6f000ca82c3300
#14 0x00005555559edb08 in sfx::SoundMixer::loadSample(char const*, bool) (this=0x555557084b30, filename=0x555559ea79e0 "Data/Sounds/Defaultfx/gui_menu_sound_mouseover.wav", temporaryCache=false) at /home/g/Games/shadowgrounds/sound/SoundMixer.cpp:997
        __PRETTY_FUNCTION__ = "sfx::SoundSample* sfx::SoundMixer::loadSample(const char*, bool)"
#15 0x00005555555fa050 in game::GameUI::playSoundEffect(char const*, float, float, float, bool, int, float, int, bool) (this=0x5555564af480, filename=0x555559ea79e0 "Data/Sounds/Defaultfx/gui_menu_sound_mouseover.wav", x=0, y=0, z=0, loop=false, volume=100, range=999, priority=20, ambient=false) at /home/g/Games/shadowgrounds/game/GameUI.cpp:5224
---Type <return> to continue, or q <return> to quit---
        s = 0x0
#16 0x00005555555fec87 in game::GameUI::playGUISound(char const*, int) (this=0x5555564af480, filename=0x555559ea79e0 "Data/Sounds/Defaultfx/gui_menu_sound_mouseover.wav", relativeVolume=100) at /home/g/Games/shadowgrounds/game/GameUI.cpp:6569
        campos = {x = 0, y = 0, z = 0}
#17 0x0000555555732483 in ui::MenuBaseImpl::CursorEvent(OguiButtonEvent*) (this=0x555559ea7010, eve=0x555559ed85f0)
    at /home/g/Games/shadowgrounds/ui/MenuBaseImpl.cpp:320
#18 0x000055555581dc28 in ui::MainMenu::CursorEvent(OguiButtonEvent*) (this=0x555559ea7010, eve=0x555559ed85f0)
    at /home/g/Games/shadowgrounds/ui/Mainmenu.cpp:230
        __PRETTY_FUNCTION__ = "virtual void ui::MainMenu::CursorEvent(OguiButtonEvent*)"
#19 0x000055555585fbf6 in ogui_button_event_handler(OguiButtonEvent::EVENT_TYPE) (et=OguiButtonEvent::EVENT_TYPE_OVER)
    at /home/g/Games/shadowgrounds/ogui/OguiWindow.cpp:41
        eve = 0x555559ed85f0
        b = 0x555559e8fa10
#20 0x000055555585fca4 in ogui_button_over_handler() () at /home/g/Games/shadowgrounds/ogui/OguiWindow.cpp:66
#21 0x0000555555863950 in og_run_gui() () at /home/g/Games/shadowgrounds/ogui/orvgui2.cpp:787
        g = 0
        add_speed = 0
        cursor_out = 0x5555564af480
#22 0x0000555555847a66 in Ogui::Run(int) (this=0x555556ade070, timeDelta=17) at /home/g/Games/shadowgrounds/ogui/Ogui.cpp:862
#23 0x00005555555b0efe in main(int, char**) (argc=2, argv=0x7fffffffe7d8)
    at /home/g/Games/shadowgrounds/shadowgrounds/shadowgrounds.cpp:1265
        maxfps = 0
        oguiTimeDelta = 17
        sbox = 0x0
        soundCmdOn = true
        musicPlaylist = 0x555557279720
        movementTime = 6869
        lastOguiUpdateTime = 6852
        vm = <incomplete type>
        show_fps = false
        no_joystick = false
        soundLib = 0x555556e50840
---Type <return> to continue, or q <return> to quit---
        bgCol = {r = 0, g = 0, b = 0}
        gc = 0x555557309610
        curTime = 6869
        path = "/home/g/.frozenbyte/shadowgrounds/log.txt"
        ctrlinit = 63
        gameUI = 0x5555564af480
        polysps = 6415
        main_config = {data = {px = 0x555556422930}}
        s3d = 0x555556455540
        mouse_sensitivity = 1
        disable_camera_timing = false
        stormInitSucces = true
        soundMixer = 0x555557084b30
        fps = 59
        errorWhine = 247
        no_keyboard = false
        no_delta_time_limit = false
        camera_mode = 3
        loadscr_str = ""
        load_fname = 0x7fffffffe520 ""
        game = 0x7fffd8007d70
        frameCountTime = 6869
        polys = 0
        tex_detail_level = 50
        ogdrv = 0x555556ac7ec0
        quitRequested = false
        windowedMode = 1
        configFile = {streamBuffer = {px = 0x555556422910, pn = {pi_ = 0x5555564229c0}}}
        errorWin = 0x555556e51280
        startTime = 4123
        gameCountTime = 6853
        compileOnly = 0
---Type <return> to continue, or q <return> to quit---
        show_polys = false
        proceduralProperties = {data = {px = 0x555556533b60}}
        camera_time_factor = 1
        vsync = false
        frames = 0
        modSelector = {data = {px = 0x5555563d15d0}}
        no_mouse = false
        visRange = 400
        ogui = 0x555556ade070
        curUnfactoredTime = 6869

```

**Comment by neuromancer** [comment]
Also, the menu screen looks corrupted:

![shot](https://user-images.githubusercontent.com/110782/30826687-d6e021c0-a20d-11e7-85f9-ffbca95e7ecc.png)

**Comment by neuromancer** [comment]
Any updates on this issue?

**Comment by vayerx** [comment]
I couldn't reproduce this crash yet, but I've found several (other?) errors. Unfortunately, I don't have much time to fix all of them quickly.
Have you tried to run the latest version (Oct 2, 2017, 2e7f731)?
By the way, if you have any patches, you are welcome to make pull requests.

**Comment by neuromancer** [comment]
I just tried the last version. I got the same crash. Btw, this is the output in the console:

```
Opening missing files log: /tmp/filelrmTm4
Opening missing files backtraces: /tmp/fileAqRNe0
error creating shader procedural_vertex_shader: line 1, column 1:  error: invalid vertex program header

error creating shader procedural_pixel_shader: line 1, column 1:  error: invalid fragment program header

error creating shader procedural_offset_pixel_shader: line 1, column 1:  error: invalid fragment program header

gl error at /home/g/Games/shadowgrounds/storm/storm3dv2/Storm3D.cpp:202: 502 invalid operation
stack trace:
  ./shadowgrounds : ()+0x2edd02
  ./shadowgrounds : ()+0x2ee452
  ./shadowgrounds : ()+0x316248
  ./shadowgrounds : ()+0x317ccc
  ./shadowgrounds : ()+0x317989
  ./shadowgrounds : ()+0x5bc36
error creating shader nv_shadow_pixel_shader_smooth: line 1, column 1:  error: invalid fragment program header

error creating shader nv_shadow_pixel_shader: line 1, column 1:  error: invalid fragment program header

error creating shader nv_noshadow_pixel_shader: line 1, column 1:  error: invalid fragment program header

error creating shader nv_cone_pixel_shader_texture: line 1, column 1:  error: invalid fragment program header

error creating shader nv_cone_pixel_shader_notexture: line 1, column 1:  error: invalid fragment program header

error creating shader cone_stencil_vertex_shader: line 1, column 1:  error: invalid vertex program header

gl error at /home/g/Games/shadowgrounds/storm/storm3dv2/render.cpp:589: 502 invalid operation
stack trace:
  ./shadowgrounds : ()+0x2edd02
  ./shadowgrounds : ()+0x2ee452
  ./shadowgrounds : ()+0x3e718e
  ./shadowgrounds : ()+0x327bd3
  ./shadowgrounds : ()+0x32810d
  ./shadowgrounds : ()+0x3273ca
  ./shadowgrounds : ()+0x317d2a
  ./shadowgrounds : ()+0x317989
  ./shadowgrounds : ()+0x5bc36
error creating shader fake_shadow_plane_vertex_shader: line 1, column 1:  error: invalid vertex program header

error creating shader fake_depth_pixel_shader: line 1, column 1:  error: invalid fragment program header

error creating shader fake_shadow_pixel_shader: line 1, column 1:  error: invalid fragment program header

gl error at /home/g/Games/shadowgrounds/storm/storm3dv2/render.cpp:804: 502 invalid operation
stack trace:
  ./shadowgrounds : ()+0x2edd02
  ./shadowgrounds : ()+0x2ee452
  ./shadowgrounds : ()+0x3e7ead
  ./shadowgrounds : ()+0x3c35e4
  ./shadowgrounds : ()+0x3c0263
  ./shadowgrounds : ()+0x317d46
  ./shadowgrounds : ()+0x317989
  ./shadowgrounds : ()+0x5bc36
error creating shader default_shader: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_0light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_0light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_0light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_1light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_1light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_1light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_2light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_2light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_2light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_3light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_3light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_3light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_4light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_4light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_4light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_5light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_5light_localreflection: line 1, column 1:  error: invalid vertex program header

error creating shader lighting_shader_5light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader skybox_shader: line 1, column 1:  error: invalid vertex program header

error creating shader default_projection_shader_dir: line 1, column 1:  error: invalid vertex program header

error creating shader default_projection_shader_point: line 1, column 1:  error: invalid vertex program header

error creating shader default_projection_shader_flat: line 1, column 1:  error: invalid vertex program header

error creating shader bone_shader_1: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_0light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_0light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_1light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_1light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_2light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_2light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_3light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_3light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_4light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_4light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_5light_noreflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_lighting_shader_5light_reflection: line 1, column 1:  error: invalid vertex program header

error creating shader bone_projection_shader_dir: line 1, column 1:  error: invalid vertex program header

error creating shader bone_projection_shader_point: line 1, column 1:  error: invalid vertex program header

error creating shader bone_projection_shader_flat: line 1, column 1:  error: invalid vertex program header

error creating shader fake_depth_vertex_shader: line 1, column 1:  error: invalid vertex program header

error creating shader fake_shadow_vertex_shader: line 1, column 1:  error: invalid vertex program header

error creating shader fake_depth_bone_vertex_shader: line 1, column 1:  error: invalid vertex program header

error creating shader fake_shadow_bone_vertex_shader: line 1, column 1:  error: invalid vertex program header

gl error at /home/g/Games/shadowgrounds/storm/storm3dv2/render.cpp:589: 502 invalid operation
stack trace:
  ./shadowgrounds : ()+0x2edd02
  ./shadowgrounds : ()+0x2ee452
  ./shadowgrounds : ()+0x3e718e
  ./shadowgrounds : ()+0x317d97
  ./shadowgrounds : ()+0x317989
  ./shadowgrounds : ()+0x5bc36
error creating shader basic_bone_lighting_shader_1: line 1, column 1:  error: invalid vertex program header

gl error at /home/g/Games/shadowgrounds/storm/storm3dv2/Storm3D_Mesh.cpp:715: 502 invalid operation
stack trace:
  ./shadowgrounds : ()+0x2edd02
  ./shadowgrounds : ()+0x2ee452
  ./shadowgrounds : ()+0x332ff6
  ./shadowgrounds : ()+0x33c643
  ./shadowgrounds : ()+0x4ba34a
  ./shadowgrounds : ()+0x4b4593
  ./shadowgrounds : ()+0x241d34
  ./shadowgrounds : ()+0x95f40
  ./shadowgrounds : ()+0x5c849
error creating shader basic_bone_lighting_shader_1: line 1, column 1:  error: invalid vertex program header

error creating shader basic_bone_lighting_shader_1: line 1, column 1:  error: invalid vertex program header
```

**Comment by monreal** [comment]
I have a similar problem. Is there any information on what game data is actually supported and how it has to be modified/prepared for use with these binaries? I own the games on Steam as well as Humble.

**Comment by vayerx** [comment]
I run games using HumbleBundle data:

    7c9913f754168742973edfeb66ba8f1c  shadowgroundsUpdate1.run
    6c38a1f3fe555b4d3f3e0a9a81a7d743  survivorUpdate1.run

**Comment by neuromancer** [comment]
Can you share the hashes of the data*.fbz files?

**Comment by neuromancer** [comment]
These are mine:

e1ee732fee3ba29a8354cef0f32c88b0  data1.fbz
d82d4e81b2384f217831d2257a7b42b1  data2.fbz
8ead40992e31deac090479c22c4a625d  data3.fbz
7c083b2e17892e8735d32266536c1ceb  data4.fbz

**Comment by vayerx** [comment]
Shadowgrounds:

    bdc715b9d4a1a4dbccc010c15a4d522e  data1.fbz

Survivor:

    e6fb6c204efc5da309981bb62edd65fa  data1.fbz
    04766baf2cc387c5cac8e3fd06d68e93  data2.fbz
    3495083f9be16fee87175fb36fc5a1e2  data3.fbz
    e5febc6a3ff926fc724f659f8bcdc3ad  data4.fbz
    080ae2082d036b761430678a3f239a16  data5.fbz

**Comment by monreal** [comment]
Using the Version from HumbleBundle (same md5sums as the ones above) I actually got the game to start, however it still complains about a few hundred missing files, like:

```
E: Could not find Texture: data/models/particles/emitter_shapes/soapy.tga
data/models/particles/emitter_shapes/soapy.tga
Missing file: 'data/models/particles/emitter_shapes/soapy.tga' E: Could not find Texture: data/models/particles/emitter_shapes/soapy.tga
data/models/particles/emitter_shapes/soapy.tg
```

or

```
Missing file: 'data/sounds/aliens/scyworm/scyworm_die1.wav' data/sounds/aliens/scyworm/scyworm_die2.wav
Missing file: 'data/sounds/aliens/scyworm/scyworm_die2.wav' data/sounds/aliens/scyworm/scyworm_die3.wav
Missing file: 'data/sounds/aliens/scyworm/scyworm_die3.wav' data/sounds/aliens/spitworm/spit_attack3.wav
Missing file: 'data/sounds/aliens/spitworm/spit_attack3.wav' data/sounds/aliens/tiny_scavenger/tiny_scavenger_idle5.wav
Missing file: 'data/sounds/aliens/tiny_scavenger/tiny_scavenger_idle5.wav' data/sounds/aliens/tiny_scavenger/tiny_scavenger_idle6.wav
```
